Repository AY2223S1-CS2103T-W10-4/tp, pull requests merged in 2022-10, with the labels that each got.

#47 Add string singularization/pluralization util
  src/main/java/modtrekt/commons/util/StringUtil.java
Labels: type.Enhancement, priority.Medium

#46 Implement module UI
  src/main/java/modtrekt/commons/util/StringUtil.java
  src/main/java/modtrekt/model/module/Module.java
  src/main/java/modtrekt/ui/MainWindow.java
  src/main/java/modtrekt/ui/modules/ModuleCard.java
  src/main/java/modtrekt/ui/modules/ModuleListPanel.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/modules/ModuleCard.fxml
  src/main/resources/view/modules/ModuleListPanel.fxml
Labels: type.Task, priority.High

#62 Implement task archiving
  src/main/java/modtrekt/commons/util/LambdaExceptionUtil.java
  src/main/java/modtrekt/logic/commands/tasks/ArchiveTaskCommand.java
  src/main/java/modtrekt/logic/commands/tasks/ListTasksCommand.java
  src/main/java/modtrekt/logic/commands/tasks/UnarchiveTaskCommand.java
  src/main/java/modtrekt/logic/parser/ArgumentTokenizer.java
  src/main/java/modtrekt/logic/parser/CliSyntax.java
  src/main/java/modtrekt/logic/parser/TaskBookParser.java
  src/main/java/modtrekt/logic/parser/tasks/ArchiveTaskCommandParser.java
  src/main/java/modtrekt/logic/parser/tasks/ListTasksCommandParser.java
  src/main/java/modtrekt/logic/parser/tasks/UnarchiveTaskCommandParser.java
  src/main/java/modtrekt/logic/parser/util/CommandParser.java
  src/main/java/modtrekt/logic/parser/util/CommandParserBuilder.java
  src/main/java/modtrekt/logic/parser/util/ParsedCommand.java
  src/main/java/modtrekt/model/Model.java
  src/main/java/modtrekt/model/module/Module.java
  src/main/java/modtrekt/model/task/Deadline.java
  src/main/java/modtrekt/model/task/Task.java
  src/main/java/modtrekt/model/util/SampleDataUtil.java
  src/main/java/modtrekt/storage/JsonAdaptedTask.java
  src/main/java/modtrekt/ui/TaskCard.java
  src/test/java/modtrekt/testutil/TaskBuilder.java
  src/test/java/modtrekt/testutil/TaskUtil.java
Labels: type.Story, priority.High

#90 Add JCommander dependency
  build.gradle
Labels: type.Task

#96 Add DG section on archiving implementation
  docs/DeveloperGuide.md
  docs/diagrams/tasks/ArchivalActivityDiagram.puml
  docs/diagrams/tasks/ListingSequenceDiagram.puml
  docs/images/tasks/ArchivalActivityDiagram.png
  docs/images/tasks/ListingSequenceDiagram.png
Labels: priority.High

#100 Implement `prioritize` command
  src/main/java/modtrekt/logic/commands/tasks/ArchiveTaskCommand.java
  src/main/java/modtrekt/logic/commands/tasks/PrioritizeTaskCommand.java
  src/main/java/modtrekt/logic/commands/tasks/UnarchiveTaskCommand.java
  src/main/java/modtrekt/logic/parser/AddTaskCommandParser.java
  src/main/java/modtrekt/logic/parser/ModtrektParser.java
  src/main/java/modtrekt/logic/parser/converters/IndexConverter.java
  src/main/java/modtrekt/logic/parser/converters/PriorityConverter.java
  src/main/java/modtrekt/model/ModelManager.java
  src/main/java/modtrekt/model/task/Deadline.java
  src/main/java/modtrekt/model/task/Description.java
  src/main/java/modtrekt/model/task/Task.java
  src/main/java/modtrekt/model/util/SampleDataUtil.java
  src/main/java/modtrekt/storage/JsonAdaptedTask.java
  src/main/java/modtrekt/ui/tasks/TaskCard.java
  src/test/java/modtrekt/logic/LogicManagerTest.java
  src/test/java/modtrekt/logic/commands/PrioritizeTaskCommandTest.java
  src/test/java/modtrekt/logic/parser/ModtrektParserTest.java
  src/test/java/modtrekt/testutil/TaskBuilder.java
Labels: type.Story, priority.High

#103 Add Avatar
  src/main/java/modtrekt/ui/ResultDisplay.java
  src/main/resources/images/snorlax.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Low

#106 Implementation of Mark Done Module
  src/main/java/modtrekt/logic/commands/DoneModuleCommand.java
  src/main/java/modtrekt/logic/commands/UndoneModuleCommand.java
  src/main/java/modtrekt/logic/parser/ModtrektParser.java
  src/main/java/modtrekt/model/module/Module.java
  src/main/java/modtrekt/ui/modules/ModuleCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProfileSidePanel.fxml
  src/test/java/modtrekt/logic/commands/DoneModuleCommandTest.java
  src/test/java/modtrekt/logic/commands/UndoneModuleCommandTest.java
Labels: type.Story, priority.Medium

#118 Week 11 calculator
  src/main/java/modtrekt/logic/commands/CommandResult.java
  src/main/java/modtrekt/model/util/SampleDataUtil.java
  src/main/java/modtrekt/storage/JsonAdaptedModule.java
  src/main/java/modtrekt/ui/MainWindow.java
  src/main/java/modtrekt/ui/ProfileSidePanel.java
  src/main/resources/view/modules/ModuleCard.fxml
Labels: priority.High

#145 fix symbols in description bug
  docs/UserGuide.md
  src/main/java/modtrekt/model/task/Description.java
Labels: type.Bug, priority.High

#142 handle module parsing for failed HTTP requests
  docs/DeveloperGuide.md
  src/main/java/modtrekt/logic/parser/module/ModuleParser.java
  src/main/java/modtrekt/logic/parser/module/data/modules.json
  src/main/java/modtrekt/model/module/Module.java
Labels: type.Enhancement, type.Task

#147 Week 11 filter modules
  src/main/java/modtrekt/logic/commands/ListModulesCommand.java
  src/main/java/modtrekt/logic/parser/ModtrektParser.java
  src/main/java/modtrekt/model/Model.java
Labels: priority.High

#153 convert remove module command to utilise module code instead of index
  src/main/java/modtrekt/commons/core/Messages.java
  src/main/java/modtrekt/logic/commands/RemoveModuleCommand.java
Labels: type.Enhancement, priority.High

#151 Add edge case for 'List mod' command
  src/main/java/modtrekt/logic/commands/DoneModuleCommand.java
  src/main/java/modtrekt/logic/commands/ListModulesCommand.java
  src/main/java/modtrekt/logic/commands/UndoneModuleCommand.java
Labels: priority.High, severity.High

#162 docs(ug): fix command table and some errors
  docs/UserGuide.md
Labels: priority.High

#198 Fix ug bugs
  docs/UserGuide.md
  docs/images/UserGuidePictures/add-mod-verbose-sample.png
Labels: type.Bug

#165 docs: improve styling and enable localhosting
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
Labels: type.Task

#207 Fix Images not working in DG
  docs/diagrams/ModulePUMLs/ModuleDone/ModuleDonePathExecution.puml
  docs/diagrams/ModulePUMLs/ModuleDone/ModuleDoneSequenceDiagram.puml
  docs/diagrams/ModulePUMLs/ModuleList/ListingModulePathExecution.puml
  docs/diagrams/ModulePUMLs/ModuleList/ListingModuleSequenceDiagram.puml
  docs/images/ModulePUMLs/DoneModule/ModuleDonePathExecution.png
  docs/images/ModulePUMLs/DoneModule/ModuleDoneSequenceDiagram.png
  docs/images/ModulePUMLs/ListModule/ListingModulePathExecution.png
  docs/images/ModulePUMLs/ListModule/ListingModuleSequenceDiagram.png
Labels: type.Bug, severity.Low
